openapi: 3.0.0
info:
  title: MD5 Hash Lookup API
  version: 1.0.0
servers:
  - url: https://md5ch.azurewebsites.net/
paths:
  /md5/{md5hash}:
    get:
      summary: Retrieves the original value of a given MD5 hash
      parameters:
        - in: path
          name: md5hash
          required: true
          schema:
            type: string
          description: The MD5 hash to look up
      responses:
        '200':
          description: Information about the hash, whether found or not.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      credit:
                        type: object
                        properties:
                          link:
                            type: string
                          name:
                            type: string
                      found:
                        type: boolean
                      hash:
                        type: string
                      hexpass:
                        type: string
                      hits:
                        type: integer
                      pass:
                        type: string
                      sysmsg:
                        type: array
                        items:
                          type: string
